### ISSUE TITLE
Permissions all messed up

### ISSUE THREAD

**Issue by laapsaap** [tbridge/munki-in-a-box#15]
I installed everything using sudo munkiinabox.sh.

But when running AutoPkgr, I get permission errors one after another. Because in GUI i run a normal user and all the directories are now root user.

So what is the recommended way with permissions?

**Comment by tbridge** [comment]
Hi!

Did you change the admin username in the script before running it?

Tom

Tom Bridge, Partner
Technolutionary LLC
"Technically, We Can Help."
m 571.243.3135

**Comment by laapsaap** [comment]
Hi,

No, I didnt change anything in the config. So I guess thats the problem? Perhaps it should check if user exist or not.

But!  Everything else works great! Been using it for a week, going to use in production. Thank you
