### ISSUE TITLE
autopkg downloader is failing

### ISSUE THREAD

**Issue by tallfunnyjew** [tbridge/munki-in-a-box#16]
rest of the script still works really well. if i manually install autopkg everything else works. spit out from the terminal log:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 0
curl: (3) <url> malformed
installer: Error the package path specified was invalid: 'autopkg-latest1.pkg'.

KEY LINE IN QUESTION:
AUTOPKG_LATEST=$(curl https://api.github.com/repos/autopkg/autopkg/releases | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["assets"][0]["browser_download_url"]')

**Comment by tbridge** [comment]
Hey there! 

I just tried that section here locally, and it is downloading and installing correctly - it's possible there was a passing error at the github api that has since passed.

You can run those sections directly at the command line and see how they go, but it should work.

**Comment by tallfunnyjew** [comment]
will try again. thanks for the quick response!
