### ISSUE TITLE
$REPOLOC 

### ISSUE THREAD

**Issue by ThomasHolbrook** [tbridge/munki-in-a-box#9]
$REPOLOC is defined on line 20 typically as "/Users/Shared/" which is fine when combined with $REPONAME to build $REPODIR but when used elsewhere in the script such as line 70 '$REPOLOC/munkitools.dmg' you end up with a double forward slash /Users/Shared//munkitools.dmg.

Propose the trailing / is dropped from $REPOLOC and line 22 is changed to include the / i.e : REPODIR=${REPOLOC}/${REPONAME}

**Comment by homebysix** [comment]
@ThomasHolbrook this should be fixed in 1.0.1.

**Comment by tbridge** [comment]
Apologies for leaving this open so long. Should be addressed by 1.0.1.
